package com.e.relojledbluetooth.Fragments;

import android.graphics.Color;
import android.os.Bundle;
import android.util.DisplayMetrics;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TableLayout;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.e.relojledbluetooth.MainActivity;
import com.e.relojledbluetooth.R;

public class PageFragment4 extends Fragment implements View.OnClickListener {

    ViewGroup rootView;
    TableLayout table_base;
    LinearLayout row1, row2, row3, row4, row5, row6, row7, row8;
    LinearLayout box1, box2, box3, box4, box5, box6, box7, box8, box9, box10, box11, box12, box13, box14, box15, box16, box17, box18, box19, box20, box21, box22, box23, box24, box25, box26, box27, box28, box29, box30, box31, box32, box33, box34, box35, box36, box37, box38, box39, box40, box41, box42, box43, box44, box45, box46, box47, box48, box49, box50, box51, box52, box53, box54, box55, box56, box57, box58, box59, box60, box61, box62, box63, box64;
    Button b1r,b2r,b3r,b4r,b5r,b6r,b7r,b8r,b9r,b10r,b11r,b12r,b13r,b14r,b15r,b16r,b17r,b18r,b19r,b20r,b21r,b22r,b23r,b24r,b25r,b26r,b27r,b28r,b29r,b30r,b31r,b32r,b33r,b34r,b35r,b36r,b37r,b38r,b39r,b40r,b41r,b42r,b43r,b44r,b45r,b46r,b47r,b48r,b49r,b50r,b51r,b52r,b53r,b54r,b55r,b56r,b57r,b58r,b59r,b60r,b61r,b62r,b63r,b64r; 
    Button b1v,b2v,b3v,b4v,b5v,b6v,b7v,b8v,b9v,b10v,b11v,b12v,b13v,b14v,b15v,b16v,b17v,b18v,b19v,b20v,b21v,b22v,b23v,b24v,b25v,b26v,b27v,b28v,b29v,b30v,b31v,b32v,b33v,b34v,b35v,b36v,b37v,b38v,b39v,b40v,b41v,b42v,b43v,b44v,b45v,b46v,b47v,b48v,b49v,b50v,b51v,b52v,b53v,b54v,b55v,b56v,b57v,b58v,b59v,b60v,b61v,b62v,b63v,b64v; 
    ImageButton borrar, avanzar, retroceder, grabar, enviar;
    TextView numAnim;
    
    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        rootView = (ViewGroup)inflater.inflate(R.layout.page4, container, false);
        
        inicializarVistas();
        
        borrar.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                apagarBotones();
            }
        });


        return rootView;

    }

    private void inicializarVistas() {
        
        borrar = rootView.findViewById(R.id.borrarBTN);
        avanzar = rootView.findViewById(R.id.avanzarBTN);
        retroceder = rootView.findViewById(R.id.retrocederBTN);
        grabar = rootView.findViewById(R.id.grabarBTN);
        enviar = rootView.findViewById(R.id.enviarBTN);
        
        numAnim = rootView.findViewById(R.id.num_animTV);
        
        table_base = rootView.findViewById(R.id.table_layout_base);

        row1 = rootView.findViewById(R.id.row_1);
        row2 = rootView.findViewById(R.id.row_2);
        row3 = rootView.findViewById(R.id.row_3);
        row4 = rootView.findViewById(R.id.row_4);
        row5 = rootView.findViewById(R.id.row_5);
        row6 = rootView.findViewById(R.id.row_6);
        row7 = rootView.findViewById(R.id.row_7);
        row8 = rootView.findViewById(R.id.row_8);
        box1 = rootView.findViewById(R.id.box_1);
        box2 = rootView.findViewById(R.id.box_2);
        box3 = rootView.findViewById(R.id.box_3);
        box4 = rootView.findViewById(R.id.box_4);
        box5 = rootView.findViewById(R.id.box_5);
        box6 = rootView.findViewById(R.id.box_6);
        box7 = rootView.findViewById(R.id.box_7);
        box8 = rootView.findViewById(R.id.box_8);
        box9 = rootView.findViewById(R.id.box_9);
        box10 = rootView.findViewById(R.id.box_10);
        box11 = rootView.findViewById(R.id.box_11);
        box12 = rootView.findViewById(R.id.box_12);
        box13 = rootView.findViewById(R.id.box_13);
        box14 = rootView.findViewById(R.id.box_14);
        box15 = rootView.findViewById(R.id.box_15);
        box16 = rootView.findViewById(R.id.box_16);
        box17 = rootView.findViewById(R.id.box_17);
        box18 = rootView.findViewById(R.id.box_18);
        box19 = rootView.findViewById(R.id.box_19);
        box20 = rootView.findViewById(R.id.box_20);
        box21 = rootView.findViewById(R.id.box_21);
        box22 = rootView.findViewById(R.id.box_22);
        box23 = rootView.findViewById(R.id.box_23);
        box24 = rootView.findViewById(R.id.box_24);
        box25 = rootView.findViewById(R.id.box_25);
        box26 = rootView.findViewById(R.id.box_26);
        box27 = rootView.findViewById(R.id.box_27);
        box28 = rootView.findViewById(R.id.box_28);
        box29 = rootView.findViewById(R.id.box_29);
        box30 = rootView.findViewById(R.id.box_30);
        box31 = rootView.findViewById(R.id.box_31);
        box32 = rootView.findViewById(R.id.box_32);
        box33 = rootView.findViewById(R.id.box_33);
        box34 = rootView.findViewById(R.id.box_34);
        box35 = rootView.findViewById(R.id.box_35);
        box36 = rootView.findViewById(R.id.box_36);
        box37 = rootView.findViewById(R.id.box_37);
        box38 = rootView.findViewById(R.id.box_38);
        box39 = rootView.findViewById(R.id.box_39);
        box40 = rootView.findViewById(R.id.box_40);
        box41 = rootView.findViewById(R.id.box_41);
        box42 = rootView.findViewById(R.id.box_42);
        box43 = rootView.findViewById(R.id.box_43);
        box44 = rootView.findViewById(R.id.box_44);
        box45 = rootView.findViewById(R.id.box_45);
        box46 = rootView.findViewById(R.id.box_46);
        box47 = rootView.findViewById(R.id.box_47);
        box48 = rootView.findViewById(R.id.box_48);
        box49 = rootView.findViewById(R.id.box_49);
        box50 = rootView.findViewById(R.id.box_50);
        box51 = rootView.findViewById(R.id.box_51);
        box52 = rootView.findViewById(R.id.box_52);
        box53 = rootView.findViewById(R.id.box_53);
        box54 = rootView.findViewById(R.id.box_54);
        box55 = rootView.findViewById(R.id.box_55);
        box56 = rootView.findViewById(R.id.box_56);
        box57 = rootView.findViewById(R.id.box_57);
        box58 = rootView.findViewById(R.id.box_58);
        box59 = rootView.findViewById(R.id.box_59);
        box60 = rootView.findViewById(R.id.box_60);
        box61 = rootView.findViewById(R.id.box_61);
        box62 = rootView.findViewById(R.id.box_62);
        box63 = rootView.findViewById(R.id.box_63);
        box64 = rootView.findViewById(R.id.box_64);

        b1r = rootView.findViewById(R.id.botonrojo1);
        b2r = rootView.findViewById(R.id.botonrojo2);
        b3r = rootView.findViewById(R.id.botonrojo3);
        b4r = rootView.findViewById(R.id.botonrojo4);
        b5r = rootView.findViewById(R.id.botonrojo5);
        b6r = rootView.findViewById(R.id.botonrojo6);
        b7r = rootView.findViewById(R.id.botonrojo7);
        b8r = rootView.findViewById(R.id.botonrojo8);
        b9r = rootView.findViewById(R.id.botonrojo9);
        b10r = rootView.findViewById(R.id.botonrojo10);
        b11r = rootView.findViewById(R.id.botonrojo11);
        b12r = rootView.findViewById(R.id.botonrojo12);
        b13r = rootView.findViewById(R.id.botonrojo13);
        b14r = rootView.findViewById(R.id.botonrojo14);
        b15r = rootView.findViewById(R.id.botonrojo15);
        b16r = rootView.findViewById(R.id.botonrojo16);
        b17r = rootView.findViewById(R.id.botonrojo17);
        b18r = rootView.findViewById(R.id.botonrojo18);
        b19r = rootView.findViewById(R.id.botonrojo19);
        b20r = rootView.findViewById(R.id.botonrojo20);
        b21r = rootView.findViewById(R.id.botonrojo21);
        b22r = rootView.findViewById(R.id.botonrojo22);
        b23r = rootView.findViewById(R.id.botonrojo23);
        b24r = rootView.findViewById(R.id.botonrojo24);
        b25r = rootView.findViewById(R.id.botonrojo25);
        b26r = rootView.findViewById(R.id.botonrojo26);
        b27r = rootView.findViewById(R.id.botonrojo27);
        b28r = rootView.findViewById(R.id.botonrojo28);
        b29r = rootView.findViewById(R.id.botonrojo29);
        b30r = rootView.findViewById(R.id.botonrojo30);
        b31r = rootView.findViewById(R.id.botonrojo31);
        b32r = rootView.findViewById(R.id.botonrojo32);
        b33r = rootView.findViewById(R.id.botonrojo33);
        b34r = rootView.findViewById(R.id.botonrojo34);
        b35r = rootView.findViewById(R.id.botonrojo35);
        b36r = rootView.findViewById(R.id.botonrojo36);
        b37r = rootView.findViewById(R.id.botonrojo37);
        b38r = rootView.findViewById(R.id.botonrojo38);
        b39r = rootView.findViewById(R.id.botonrojo39);
        b40r = rootView.findViewById(R.id.botonrojo40);
        b41r = rootView.findViewById(R.id.botonrojo41);
        b42r = rootView.findViewById(R.id.botonrojo42);
        b43r = rootView.findViewById(R.id.botonrojo43);
        b44r = rootView.findViewById(R.id.botonrojo44);
        b45r = rootView.findViewById(R.id.botonrojo45);
        b46r = rootView.findViewById(R.id.botonrojo46);
        b47r = rootView.findViewById(R.id.botonrojo47);
        b48r = rootView.findViewById(R.id.botonrojo48);
        b49r = rootView.findViewById(R.id.botonrojo49);
        b50r = rootView.findViewById(R.id.botonrojo50);
        b51r = rootView.findViewById(R.id.botonrojo51);
        b52r = rootView.findViewById(R.id.botonrojo52);
        b53r = rootView.findViewById(R.id.botonrojo53);
        b54r = rootView.findViewById(R.id.botonrojo54);
        b55r = rootView.findViewById(R.id.botonrojo55);
        b56r = rootView.findViewById(R.id.botonrojo56);
        b57r = rootView.findViewById(R.id.botonrojo57);
        b58r = rootView.findViewById(R.id.botonrojo58);
        b59r = rootView.findViewById(R.id.botonrojo59);
        b60r = rootView.findViewById(R.id.botonrojo60);
        b61r = rootView.findViewById(R.id.botonrojo61);
        b62r = rootView.findViewById(R.id.botonrojo62);
        b63r = rootView.findViewById(R.id.botonrojo63);
        b64r = rootView.findViewById(R.id.botonrojo64);

        b1v = rootView.findViewById(R.id.botonverde1);
        b2v = rootView.findViewById(R.id.botonverde2);
        b3v = rootView.findViewById(R.id.botonverde3);
        b4v = rootView.findViewById(R.id.botonverde4);
        b5v = rootView.findViewById(R.id.botonverde5);
        b6v = rootView.findViewById(R.id.botonverde6);
        b7v = rootView.findViewById(R.id.botonverde7);
        b8v = rootView.findViewById(R.id.botonverde8);
        b9v = rootView.findViewById(R.id.botonverde9);
        b10v = rootView.findViewById(R.id.botonverde10);
        b11v = rootView.findViewById(R.id.botonverde11);
        b12v = rootView.findViewById(R.id.botonverde12);
        b13v = rootView.findViewById(R.id.botonverde13);
        b14v = rootView.findViewById(R.id.botonverde14);
        b15v = rootView.findViewById(R.id.botonverde15);
        b16v = rootView.findViewById(R.id.botonverde16);
        b17v = rootView.findViewById(R.id.botonverde17);
        b18v = rootView.findViewById(R.id.botonverde18);
        b19v = rootView.findViewById(R.id.botonverde19);
        b20v = rootView.findViewById(R.id.botonverde20);
        b21v = rootView.findViewById(R.id.botonverde21);
        b22v = rootView.findViewById(R.id.botonverde22);
        b23v = rootView.findViewById(R.id.botonverde23);
        b24v = rootView.findViewById(R.id.botonverde24);
        b25v = rootView.findViewById(R.id.botonverde25);
        b26v = rootView.findViewById(R.id.botonverde26);
        b27v = rootView.findViewById(R.id.botonverde27);
        b28v = rootView.findViewById(R.id.botonverde28);
        b29v = rootView.findViewById(R.id.botonverde29);
        b30v = rootView.findViewById(R.id.botonverde30);
        b31v = rootView.findViewById(R.id.botonverde31);
        b32v = rootView.findViewById(R.id.botonverde32);
        b33v = rootView.findViewById(R.id.botonverde33);
        b34v = rootView.findViewById(R.id.botonverde34);
        b35v = rootView.findViewById(R.id.botonverde35);
        b36v = rootView.findViewById(R.id.botonverde36);
        b37v = rootView.findViewById(R.id.botonverde37);
        b38v = rootView.findViewById(R.id.botonverde38);
        b39v = rootView.findViewById(R.id.botonverde39);
        b40v = rootView.findViewById(R.id.botonverde40);
        b41v = rootView.findViewById(R.id.botonverde41);
        b42v = rootView.findViewById(R.id.botonverde42);
        b43v = rootView.findViewById(R.id.botonverde43);
        b44v = rootView.findViewById(R.id.botonverde44);
        b45v = rootView.findViewById(R.id.botonverde45);
        b46v = rootView.findViewById(R.id.botonverde46);
        b47v = rootView.findViewById(R.id.botonverde47);
        b48v = rootView.findViewById(R.id.botonverde48);
        b49v = rootView.findViewById(R.id.botonverde49);
        b50v = rootView.findViewById(R.id.botonverde50);
        b51v = rootView.findViewById(R.id.botonverde51);
        b52v = rootView.findViewById(R.id.botonverde52);
        b53v = rootView.findViewById(R.id.botonverde53);
        b54v = rootView.findViewById(R.id.botonverde54);
        b55v = rootView.findViewById(R.id.botonverde55);
        b56v = rootView.findViewById(R.id.botonverde56);
        b57v = rootView.findViewById(R.id.botonverde57);
        b58v = rootView.findViewById(R.id.botonverde58);
        b59v = rootView.findViewById(R.id.botonverde59);
        b60v = rootView.findViewById(R.id.botonverde60);
        b61v = rootView.findViewById(R.id.botonverde61);
        b62v = rootView.findViewById(R.id.botonverde62);
        b63v = rootView.findViewById(R.id.botonverde63);
        b64v = rootView.findViewById(R.id.botonverde64);


        DisplayMetrics metrics = new DisplayMetrics();
        ((MainActivity) getActivity()).getWindowManager().getDefaultDisplay().getMetrics(metrics);
        int width = metrics.widthPixels - (metrics.widthPixels / 3); // ancho absoluto en pixels
        int height = metrics.heightPixels - (metrics.heightPixels / 3); // alto absoluto en pixels

        Log.d("Miapp", width + " x " + height);

        ViewGroup.LayoutParams params = table_base.getLayoutParams();
        // Changes the height and width to the specified *pixels*
        params.height = width;
        params.width = width;
        table_base.setLayoutParams(params);

        b1r.setOnClickListener(this);
        b2r.setOnClickListener(this);
        b3r.setOnClickListener(this);
        b4r.setOnClickListener(this);
        b5r.setOnClickListener(this);
        b6r.setOnClickListener(this);
        b7r.setOnClickListener(this);
        b8r.setOnClickListener(this);
        b9r.setOnClickListener(this);
        b10r.setOnClickListener(this);
        b11r.setOnClickListener(this);
        b12r.setOnClickListener(this);
        b13r.setOnClickListener(this);
        b14r.setOnClickListener(this);
        b15r.setOnClickListener(this);
        b16r.setOnClickListener(this);
        b17r.setOnClickListener(this);
        b18r.setOnClickListener(this);
        b19r.setOnClickListener(this);
        b20r.setOnClickListener(this);
        b21r.setOnClickListener(this);
        b22r.setOnClickListener(this);
        b23r.setOnClickListener(this);
        b24r.setOnClickListener(this);
        b25r.setOnClickListener(this);
        b26r.setOnClickListener(this);
        b27r.setOnClickListener(this);
        b28r.setOnClickListener(this);
        b29r.setOnClickListener(this);
        b30r.setOnClickListener(this);
        b31r.setOnClickListener(this);
        b32r.setOnClickListener(this);
        b33r.setOnClickListener(this);
        b34r.setOnClickListener(this);
        b35r.setOnClickListener(this);
        b36r.setOnClickListener(this);
        b37r.setOnClickListener(this);
        b38r.setOnClickListener(this);
        b39r.setOnClickListener(this);
        b40r.setOnClickListener(this);
        b41r.setOnClickListener(this);
        b42r.setOnClickListener(this);
        b43r.setOnClickListener(this);
        b44r.setOnClickListener(this);
        b45r.setOnClickListener(this);
        b46r.setOnClickListener(this);
        b47r.setOnClickListener(this);
        b48r.setOnClickListener(this);
        b49r.setOnClickListener(this);
        b50r.setOnClickListener(this);
        b51r.setOnClickListener(this);
        b52r.setOnClickListener(this);
        b53r.setOnClickListener(this);
        b54r.setOnClickListener(this);
        b55r.setOnClickListener(this);
        b56r.setOnClickListener(this);
        b57r.setOnClickListener(this);
        b58r.setOnClickListener(this);
        b59r.setOnClickListener(this);
        b60r.setOnClickListener(this);
        b61r.setOnClickListener(this);
        b62r.setOnClickListener(this);
        b63r.setOnClickListener(this);
        b64r.setOnClickListener(this);

        b1v.setOnClickListener(this);
        b2v.setOnClickListener(this);
        b3v.setOnClickListener(this);
        b4v.setOnClickListener(this);
        b5v.setOnClickListener(this);
        b6v.setOnClickListener(this);
        b7v.setOnClickListener(this);
        b8v.setOnClickListener(this);
        b9v.setOnClickListener(this);
        b10v.setOnClickListener(this);
        b11v.setOnClickListener(this);
        b12v.setOnClickListener(this);
        b13v.setOnClickListener(this);
        b14v.setOnClickListener(this);
        b15v.setOnClickListener(this);
        b16v.setOnClickListener(this);
        b17v.setOnClickListener(this);
        b18v.setOnClickListener(this);
        b19v.setOnClickListener(this);
        b20v.setOnClickListener(this);
        b21v.setOnClickListener(this);
        b22v.setOnClickListener(this);
        b23v.setOnClickListener(this);
        b24v.setOnClickListener(this);
        b25v.setOnClickListener(this);
        b26v.setOnClickListener(this);
        b27v.setOnClickListener(this);
        b28v.setOnClickListener(this);
        b29v.setOnClickListener(this);
        b30v.setOnClickListener(this);
        b31v.setOnClickListener(this);
        b32v.setOnClickListener(this);
        b33v.setOnClickListener(this);
        b34v.setOnClickListener(this);
        b35v.setOnClickListener(this);
        b36v.setOnClickListener(this);
        b37v.setOnClickListener(this);
        b38v.setOnClickListener(this);
        b39v.setOnClickListener(this);
        b40v.setOnClickListener(this);
        b41v.setOnClickListener(this);
        b42v.setOnClickListener(this);
        b43v.setOnClickListener(this);
        b44v.setOnClickListener(this);
        b45v.setOnClickListener(this);
        b46v.setOnClickListener(this);
        b47v.setOnClickListener(this);
        b48v.setOnClickListener(this);
        b49v.setOnClickListener(this);
        b50v.setOnClickListener(this);
        b51v.setOnClickListener(this);
        b52v.setOnClickListener(this);
        b53v.setOnClickListener(this);
        b54v.setOnClickListener(this);
        b55v.setOnClickListener(this);
        b56v.setOnClickListener(this);
        b57v.setOnClickListener(this);
        b58v.setOnClickListener(this);
        b59v.setOnClickListener(this);
        b60v.setOnClickListener(this);
        b61v.setOnClickListener(this);
        b62v.setOnClickListener(this);
        b63v.setOnClickListener(this);
        b64v.setOnClickListener(this);
        


   }


    @Override
    public void onClick(View v) {
        Log.d("Miapp" ,  "Pulsado: " + v.getId());

        switch (v.getTag().toString()) {
            case "v":
                v.setBackgroundColor(Color.GREEN);
                v.setTag("V");
                break;
            case "V":
                v.setBackgroundColor(Color.TRANSPARENT);
                v.setTag("v");
                break;
            case "r":
                v.setBackgroundColor(Color.RED);
                v.setTag("R");
                break;
            case "R":
                v.setBackgroundColor(Color.TRANSPARENT);
                v.setTag("r");
                break;
            default:
                break;
        }


    }

    
    public void apagarBotones(){
        b1r.setBackgroundColor(Color.TRANSPARENT);
        b2r.setBackgroundColor(Color.TRANSPARENT);
        b3r.setBackgroundColor(Color.TRANSPARENT);
        b4r.setBackgroundColor(Color.TRANSPARENT);
        b5r.setBackgroundColor(Color.TRANSPARENT);
        b6r.setBackgroundColor(Color.TRANSPARENT);
        b7r.setBackgroundColor(Color.TRANSPARENT);
        b8r.setBackgroundColor(Color.TRANSPARENT);
        b9r.setBackgroundColor(Color.TRANSPARENT);
        b10r.setBackgroundColor(Color.TRANSPARENT);
        b11r.setBackgroundColor(Color.TRANSPARENT);
        b12r.setBackgroundColor(Color.TRANSPARENT);
        b13r.setBackgroundColor(Color.TRANSPARENT);
        b14r.setBackgroundColor(Color.TRANSPARENT);
        b15r.setBackgroundColor(Color.TRANSPARENT);
        b16r.setBackgroundColor(Color.TRANSPARENT);
        b17r.setBackgroundColor(Color.TRANSPARENT);
        b18r.setBackgroundColor(Color.TRANSPARENT);
        b19r.setBackgroundColor(Color.TRANSPARENT);
        b20r.setBackgroundColor(Color.TRANSPARENT);
        b21r.setBackgroundColor(Color.TRANSPARENT);
        b22r.setBackgroundColor(Color.TRANSPARENT);
        b23r.setBackgroundColor(Color.TRANSPARENT);
        b24r.setBackgroundColor(Color.TRANSPARENT);
        b25r.setBackgroundColor(Color.TRANSPARENT);
        b26r.setBackgroundColor(Color.TRANSPARENT);
        b27r.setBackgroundColor(Color.TRANSPARENT);
        b28r.setBackgroundColor(Color.TRANSPARENT);
        b29r.setBackgroundColor(Color.TRANSPARENT);
        b30r.setBackgroundColor(Color.TRANSPARENT);
        b31r.setBackgroundColor(Color.TRANSPARENT);
        b32r.setBackgroundColor(Color.TRANSPARENT);
        b33r.setBackgroundColor(Color.TRANSPARENT);
        b34r.setBackgroundColor(Color.TRANSPARENT);
        b35r.setBackgroundColor(Color.TRANSPARENT);
        b36r.setBackgroundColor(Color.TRANSPARENT);
        b37r.setBackgroundColor(Color.TRANSPARENT);
        b38r.setBackgroundColor(Color.TRANSPARENT);
        b39r.setBackgroundColor(Color.TRANSPARENT);
        b40r.setBackgroundColor(Color.TRANSPARENT);
        b41r.setBackgroundColor(Color.TRANSPARENT);
        b42r.setBackgroundColor(Color.TRANSPARENT);
        b43r.setBackgroundColor(Color.TRANSPARENT);
        b44r.setBackgroundColor(Color.TRANSPARENT);
        b45r.setBackgroundColor(Color.TRANSPARENT);
        b46r.setBackgroundColor(Color.TRANSPARENT);
        b47r.setBackgroundColor(Color.TRANSPARENT);
        b48r.setBackgroundColor(Color.TRANSPARENT);
        b49r.setBackgroundColor(Color.TRANSPARENT);
        b50r.setBackgroundColor(Color.TRANSPARENT);
        b51r.setBackgroundColor(Color.TRANSPARENT);
        b52r.setBackgroundColor(Color.TRANSPARENT);
        b53r.setBackgroundColor(Color.TRANSPARENT);
        b54r.setBackgroundColor(Color.TRANSPARENT);
        b55r.setBackgroundColor(Color.TRANSPARENT);
        b56r.setBackgroundColor(Color.TRANSPARENT);
        b57r.setBackgroundColor(Color.TRANSPARENT);
        b58r.setBackgroundColor(Color.TRANSPARENT);
        b59r.setBackgroundColor(Color.TRANSPARENT);
        b60r.setBackgroundColor(Color.TRANSPARENT);
        b61r.setBackgroundColor(Color.TRANSPARENT);
        b62r.setBackgroundColor(Color.TRANSPARENT);
        b63r.setBackgroundColor(Color.TRANSPARENT);
        b64r.setBackgroundColor(Color.TRANSPARENT);

        b1v.setBackgroundColor(Color.TRANSPARENT);
        b2v.setBackgroundColor(Color.TRANSPARENT);
        b3v.setBackgroundColor(Color.TRANSPARENT);
        b4v.setBackgroundColor(Color.TRANSPARENT);
        b5v.setBackgroundColor(Color.TRANSPARENT);
        b6v.setBackgroundColor(Color.TRANSPARENT);
        b7v.setBackgroundColor(Color.TRANSPARENT);
        b8v.setBackgroundColor(Color.TRANSPARENT);
        b9v.setBackgroundColor(Color.TRANSPARENT);
        b10v.setBackgroundColor(Color.TRANSPARENT);
        b11v.setBackgroundColor(Color.TRANSPARENT);
        b12v.setBackgroundColor(Color.TRANSPARENT);
        b13v.setBackgroundColor(Color.TRANSPARENT);
        b14v.setBackgroundColor(Color.TRANSPARENT);
        b15v.setBackgroundColor(Color.TRANSPARENT);
        b16v.setBackgroundColor(Color.TRANSPARENT);
        b17v.setBackgroundColor(Color.TRANSPARENT);
        b18v.setBackgroundColor(Color.TRANSPARENT);
        b19v.setBackgroundColor(Color.TRANSPARENT);
        b20v.setBackgroundColor(Color.TRANSPARENT);
        b21v.setBackgroundColor(Color.TRANSPARENT);
        b22v.setBackgroundColor(Color.TRANSPARENT);
        b23v.setBackgroundColor(Color.TRANSPARENT);
        b24v.setBackgroundColor(Color.TRANSPARENT);
        b25v.setBackgroundColor(Color.TRANSPARENT);
        b26v.setBackgroundColor(Color.TRANSPARENT);
        b27v.setBackgroundColor(Color.TRANSPARENT);
        b28v.setBackgroundColor(Color.TRANSPARENT);
        b29v.setBackgroundColor(Color.TRANSPARENT);
        b30v.setBackgroundColor(Color.TRANSPARENT);
        b31v.setBackgroundColor(Color.TRANSPARENT);
        b32v.setBackgroundColor(Color.TRANSPARENT);
        b33v.setBackgroundColor(Color.TRANSPARENT);
        b34v.setBackgroundColor(Color.TRANSPARENT);
        b35v.setBackgroundColor(Color.TRANSPARENT);
        b36v.setBackgroundColor(Color.TRANSPARENT);
        b37v.setBackgroundColor(Color.TRANSPARENT);
        b38v.setBackgroundColor(Color.TRANSPARENT);
        b39v.setBackgroundColor(Color.TRANSPARENT);
        b40v.setBackgroundColor(Color.TRANSPARENT);
        b41v.setBackgroundColor(Color.TRANSPARENT);
        b42v.setBackgroundColor(Color.TRANSPARENT);
        b43v.setBackgroundColor(Color.TRANSPARENT);
        b44v.setBackgroundColor(Color.TRANSPARENT);
        b45v.setBackgroundColor(Color.TRANSPARENT);
        b46v.setBackgroundColor(Color.TRANSPARENT);
        b47v.setBackgroundColor(Color.TRANSPARENT);
        b48v.setBackgroundColor(Color.TRANSPARENT);
        b49v.setBackgroundColor(Color.TRANSPARENT);
        b50v.setBackgroundColor(Color.TRANSPARENT);
        b51v.setBackgroundColor(Color.TRANSPARENT);
        b52v.setBackgroundColor(Color.TRANSPARENT);
        b53v.setBackgroundColor(Color.TRANSPARENT);
        b54v.setBackgroundColor(Color.TRANSPARENT);
        b55v.setBackgroundColor(Color.TRANSPARENT);
        b56v.setBackgroundColor(Color.TRANSPARENT);
        b57v.setBackgroundColor(Color.TRANSPARENT);
        b58v.setBackgroundColor(Color.TRANSPARENT);
        b59v.setBackgroundColor(Color.TRANSPARENT);
        b60v.setBackgroundColor(Color.TRANSPARENT);
        b61v.setBackgroundColor(Color.TRANSPARENT);
        b62v.setBackgroundColor(Color.TRANSPARENT);
        b63v.setBackgroundColor(Color.TRANSPARENT);
        b64v.setBackgroundColor(Color.TRANSPARENT);

        b1r.setTag("r");
        b2r.setTag("r");
        b3r.setTag("r");
        b4r.setTag("r");
        b5r.setTag("r");
        b6r.setTag("r");
        b7r.setTag("r");
        b8r.setTag("r");
        b9r.setTag("r");
        b10r.setTag("r");
        b11r.setTag("r");
        b12r.setTag("r");
        b13r.setTag("r");
        b14r.setTag("r");
        b15r.setTag("r");
        b16r.setTag("r");
        b17r.setTag("r");
        b18r.setTag("r");
        b19r.setTag("r");
        b20r.setTag("r");
        b21r.setTag("r");
        b22r.setTag("r");
        b23r.setTag("r");
        b24r.setTag("r");
        b25r.setTag("r");
        b26r.setTag("r");
        b27r.setTag("r");
        b28r.setTag("r");
        b29r.setTag("r");
        b30r.setTag("r");
        b31r.setTag("r");
        b32r.setTag("r");
        b33r.setTag("r");
        b34r.setTag("r");
        b35r.setTag("r");
        b36r.setTag("r");
        b37r.setTag("r");
        b38r.setTag("r");
        b39r.setTag("r");
        b40r.setTag("r");
        b41r.setTag("r");
        b42r.setTag("r");
        b43r.setTag("r");
        b44r.setTag("r");
        b45r.setTag("r");
        b46r.setTag("r");
        b47r.setTag("r");
        b48r.setTag("r");
        b49r.setTag("r");
        b50r.setTag("r");
        b51r.setTag("r");
        b52r.setTag("r");
        b53r.setTag("r");
        b54r.setTag("r");
        b55r.setTag("r");
        b56r.setTag("r");
        b57r.setTag("r");
        b58r.setTag("r");
        b59r.setTag("r");
        b60r.setTag("r");
        b61r.setTag("r");
        b62r.setTag("r");
        b63r.setTag("r");
        b64r.setTag("r");

        b1v.setTag("v");
        b2v.setTag("v");
        b3v.setTag("v");
        b4v.setTag("v");
        b5v.setTag("v");
        b6v.setTag("v");
        b7v.setTag("v");
        b8v.setTag("v");
        b9v.setTag("v");
        b10v.setTag("v");
        b11v.setTag("v");
        b12v.setTag("v");
        b13v.setTag("v");
        b14v.setTag("v");
        b15v.setTag("v");
        b16v.setTag("v");
        b17v.setTag("v");
        b18v.setTag("v");
        b19v.setTag("v");
        b20v.setTag("v");
        b21v.setTag("v");
        b22v.setTag("v");
        b23v.setTag("v");
        b24v.setTag("v");
        b25v.setTag("v");
        b26v.setTag("v");
        b27v.setTag("v");
        b28v.setTag("v");
        b29v.setTag("v");
        b30v.setTag("v");
        b31v.setTag("v");
        b32v.setTag("v");
        b33v.setTag("v");
        b34v.setTag("v");
        b35v.setTag("v");
        b36v.setTag("v");
        b37v.setTag("v");
        b38v.setTag("v");
        b39v.setTag("v");
        b40v.setTag("v");
        b41v.setTag("v");
        b42v.setTag("v");
        b43v.setTag("v");
        b44v.setTag("v");
        b45v.setTag("v");
        b46v.setTag("v");
        b47v.setTag("v");
        b48v.setTag("v");
        b49v.setTag("v");
        b50v.setTag("v");
        b51v.setTag("v");
        b52v.setTag("v");
        b53v.setTag("v");
        b54v.setTag("v");
        b55v.setTag("v");
        b56v.setTag("v");
        b57v.setTag("v");
        b58v.setTag("v");
        b59v.setTag("v");
        b60v.setTag("v");
        b61v.setTag("v");
        b62v.setTag("v");
        b63v.setTag("v");
        b64v.setTag("v");
    }

}
